#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AssurantApplication.Resource", IsApplication=true)]

namespace AssurantApplication
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::AndroidSDKLibrary.Resource.String.library_name = global::AssurantApplication.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int fontName = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f06000c
			public const int app_background = 2131099660;
			
			// aapt resource value: 0x7f060014
			public const int app_button_bg = 2131099668;
			
			// aapt resource value: 0x7f060011
			public const int app_button_color = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int app_button_color_reset = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int app_button_color_set = 2131099667;
			
			// aapt resource value: 0x7f060010
			public const int app_button_text_color = 2131099664;
			
			// aapt resource value: 0x7f060017
			public const int app_contact_list_text_color = 2131099671;
			
			// aapt resource value: 0x7f06000e
			public const int app_footerLayout = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int app_headingLayout = 2131099661;
			
			// aapt resource value: 0x7f06000f
			public const int app_heading_color = 2131099663;
			
			// aapt resource value: 0x7f060018
			public const int app_line_color = 2131099672;
			
			// aapt resource value: 0x7f060015
			public const int app_rectangle_border = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int app_search_id_bg = 2131099670;
			
			// aapt resource value: 0x7f06001a
			public const int contact_textcolor = 2131099674;
			
			// aapt resource value: 0x7f06000a
			public const int holo_blue_bright = 2131099658;
			
			// aapt resource value: 0x7f060004
			public const int holo_blue_dark = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int holo_blue_light = 2131099648;
			
			// aapt resource value: 0x7f06000b
			public const int holo_gray_bright = 2131099659;
			
			// aapt resource value: 0x7f060001
			public const int holo_gray_light = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int holo_green_dark = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int holo_green_light = 2131099650;
			
			// aapt resource value: 0x7f060009
			public const int holo_orange_dark = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int holo_orange_light = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int holo_purple = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int holo_red_dark = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int holo_red_light = 2131099651;
			
			// aapt resource value: 0x7f060019
			public const int new_rectabgle_background = 2131099673;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070000
			public const int activity_horizontal_margin = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int activity_vertical_margin = 2131165185;
			
			// aapt resource value: 0x7f07000a
			public const int arrow_line_padding_big = 2131165194;
			
			// aapt resource value: 0x7f070009
			public const int arrow_line_padding_small = 2131165193;
			
			// aapt resource value: 0x7f070008
			public const int arrow_line_size = 2131165192;
			
			// aapt resource value: 0x7f070003
			public const int contactImagesize = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int contactImagesize_small = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int grid_text_size1 = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int grid_text_size2 = 2131165191;
			
			// aapt resource value: 0x7f070002
			public const int home_text_size = 2131165186;
			
			// aapt resource value: 0x7f070005
			public const int text_size = 2131165189;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Assurant = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int logo_icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int rectangle_header = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int splash_gradient = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int submit_btn = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080021
			public const int BtnMessageOk = 2131230753;
			
			// aapt resource value: 0x7f080000
			public const int Sync = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int btnBreakDownInfo = 2131230721;
			
			// aapt resource value: 0x7f08000e
			public const int btnCreateCustomer = 2131230734;
			
			// aapt resource value: 0x7f080016
			public const int btnCreateMessage = 2131230742;
			
			// aapt resource value: 0x7f080012
			public const int btnCustomerMiscellaneouns = 2131230738;
			
			// aapt resource value: 0x7f08000f
			public const int btnCustomerWithID = 2131230735;
			
			// aapt resource value: 0x7f080002
			public const int btnEligibleCustomer = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int btnEligibleCustomerEmail = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int btnEligibleCustomerUpdate = 2131230724;
			
			// aapt resource value: 0x7f080011
			public const int btnEmailPhoneUpdate = 2131230737;
			
			// aapt resource value: 0x7f080009
			public const int btnFormCollection = 2131230729;
			
			// aapt resource value: 0x7f080008
			public const int btnFormDefinitionName = 2131230728;
			
			// aapt resource value: 0x7f080007
			public const int btnFormDefinitions = 2131230727;
			
			// aapt resource value: 0x7f08000d
			public const int btnFormDelete = 2131230733;
			
			// aapt resource value: 0x7f08000a
			public const int btnFormPost = 2131230730;
			
			// aapt resource value: 0x7f08000c
			public const int btnFormUpdate = 2131230732;
			
			// aapt resource value: 0x7f080010
			public const int btnGetCustomerWithQuery = 2131230736;
			
			// aapt resource value: 0x7f08000b
			public const int btnGetForm = 2131230731;
			
			// aapt resource value: 0x7f080017
			public const int btnGetMessage = 2131230743;
			
			// aapt resource value: 0x7f080013
			public const int btnLogOutCreate = 2131230739;
			
			// aapt resource value: 0x7f080005
			public const int btnOTPCreate = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int btnOTPValidate = 2131230726;
			
			// aapt resource value: 0x7f080015
			public const int btnSAML = 2131230741;
			
			// aapt resource value: 0x7f080018
			public const int btnShasignRead = 2131230744;
			
			// aapt resource value: 0x7f080014
			public const int btnValidateTokenCreate = 2131230740;
			
			// aapt resource value: 0x7f08001e
			public const int headingLayout = 2131230750;
			
			// aapt resource value: 0x7f080019
			public const int loginRootLayout = 2131230745;
			
			// aapt resource value: 0x7f08001b
			public const int loginStartButton = 2131230747;
			
			// aapt resource value: 0x7f080020
			public const int lvSubmit = 2131230752;
			
			// aapt resource value: 0x7f08001d
			public const int messageActivityRootLayout = 2131230749;
			
			// aapt resource value: 0x7f080022
			public const int scrollView1 = 2131230754;
			
			// aapt resource value: 0x7f08001a
			public const int textView1 = 2131230746;
			
			// aapt resource value: 0x7f08001f
			public const int textViewtitle = 2131230751;
			
			// aapt resource value: 0x7f080023
			public const int tvMessagePart1 = 2131230755;
			
			// aapt resource value: 0x7f080024
			public const int tvMessagePart2 = 2131230756;
			
			// aapt resource value: 0x7f08001c
			public const int withOutLogin = 2131230748;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Home = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Login = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Message = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050006
			public const int app_identifier = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int heading_title = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int hello = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int message_part1 = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int message_part2 = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int authenticator = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int syncadapter = 2130968577;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MyTextView = new int[] {
					2130771968};
			
			// aapt resource value: 0
			public const int MyTextView_fontName = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
